# Урок 6

## Практическое задание

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

#### Преобразуем
$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix} = 
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix} = 
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
-x_{2}+x_{3}+5x_{4}=-2, \\
-2x_{3}+3x_{4}=4.
\end{cases}$

#### Примем $x_{4}$ за с, тогда:

$\begin{cases}
x_{1} + x_{2} - x_{3} - 2x_{4} = 0, \\
-x_{2} + x_{3} + 5x_{4} = -2, \\
x_{3} = \frac{3c - 4}{2}, \\
x_{4} = c\\
\end{cases} = 
\begin{cases}
x_{1} + x_{2} - x_{3} - 2x_{4} = 0, \\
x_{2} = 2 + \frac{3c - 4}{2} + 5c = \frac{13c}{2}, \\
x_{3} = \frac{3c - 4}{2}, \\
x_{4} = c\\
\end{cases} = 
\begin{cases}
x_{1} = \frac{3c - 4}{2} - 2 - \frac{3c - 4}{2} - 5c + 2c = -2 - 3c, \\
x_{2} = 2 + \frac{3c - 4}{2} + 5c = \frac{13c}{2}, \\
x_{3} = \frac{3c - 4}{2}, \\
x_{4} = c\\
\end{cases}$

#### Ответ:

$\begin{cases}
x_{1} = -2 - 3c, \\
x_{2} = \frac{13c}{2}, \\
x_{3} = \frac{3c - 4}{2}, \\
x_{4} = c\\
\end{cases}$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

**a)**<br>
$\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1\\ 
2 & -5 & -3\\ 
1 & 1 & -1
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}$

#### Выполним перемещение

$\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1\\
3 & -1 & 1\\ 
2 & -5 & -3\\ 
\end{matrix}\right|
\begin{matrix}
0\\ 
4\\
-17
\end{matrix}
\end{pmatrix}$

#### Из третьего удвоенное первое 

$\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1\\
3 & -1 & 1\\ 
0 & -7 & -1\\ 
\end{matrix}\right|
\begin{matrix}
0\\ 
4\\
-17
\end{matrix}
\end{pmatrix}$

#### Из второго удвоенное первое 

$\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1\\
0 & -4 & 4\\ 
0 & -7 & -1\\ 
\end{matrix}\right|
\begin{matrix}
0\\ 
4\\
-17
\end{matrix}
\end{pmatrix}$

#### Разделим второе на 4

$\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1\\
0 & -1 & 1
\\ 
0 & -7 & -1\\ 
\end{matrix}\right|
\begin{matrix}
0\\ 
1\\
-17
\end{matrix}
\end{pmatrix}$

#### Из третьего уравнения второе, умноженное на 7

$\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1\\
0 & -1 & 1\\ 
0 & 0 & -8\\ 
\end{matrix}\right|
\begin{matrix}
0\\ 
1\\
-24
\end{matrix}
\end{pmatrix}$

#### Первую домножим на -1, а третью разделим на -8

$\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1\\
0 & 1 & -1\\ 
0 & 0 & 1\\ 
\end{matrix}\right|
\begin{matrix}
0\\ 
-1\\
3
\end{matrix}
\end{pmatrix}$

#### Решение (система совместна):

$\begin{cases}
x_{1} + x_{2} - x_{3} = 0, \\
x_{2} - x_{3} = -1, \\
x_{3} = 3;
\end{cases} = 
\begin{cases}
x_{1} = 1, \\
x_{2} = 2, \\
x_{3} = 3;
\end{cases}$

**б)** Система не совместна, присутствует линейная зависимость.<br>

**в)**<br>
$\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5\\
3 & 1 & -8
\end{matrix}\right|
\begin{matrix}
4\\ 
-2
\end{matrix}
\end{pmatrix}$

#### Вычтем из второй строки утроенную первую

$\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5\\
0 & -5 & -23
\end{matrix}\right|
\begin{matrix}
4\\ 
-14
\end{matrix}
\end{pmatrix}$

#### Разделим третью  на -5

$\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5\\
0 & 1 & 23/5
\end{matrix}\right|
\begin{matrix}
4\\ 
14/5
\end{matrix}
\end{pmatrix}$

#### Приравняем к константе c $x_{3}$:

$\begin{cases}
x_{1} + 2x_{2} + 5x_{3} = 4,\\
x_{2} + 23/5x_{3} = 14/5,\\
x_{3} = c
\end{cases} = 
\begin{cases}
x_{1} + 2x_{2} + 5x_{3} = 4,\\
x_{2} = 14/5 - 23/5c,\\
x_{3} = c
\end{cases} = 
\begin{cases}
x_{1} = 21/5c - 8/5,\\
x_{2} = 14/5 - 23/5x_{3},\\
x_{3} = c
\end{cases}$

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

$A=\begin{pmatrix}
\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}
\end{pmatrix} = 
\begin{pmatrix}
\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 1 & 0 & 0.2\\ 
0 & 0 & 1 & 0\\ 
0 & 0 & 0 & 1
\end{matrix}
\end{pmatrix}$

$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix} = 
\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 1 & 0 & 0.2\\ 
0 & 0 & 1 & 0\\ 
0 & 0 & 0 & 1
\end{matrix}\right|
\begin{matrix}
3\\ 
0.4\\
4/3\\
0.5
\end{matrix}
\end{pmatrix}$

####  $Rank(A) = Rank(\tilde{A}) = 4$ Система определена и имеет единственное решение.

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

$\tilde{A} = \begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}$

#### Из второй строчки первую, умноженную на 4

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & -3 & -6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b - 4a\\
c
\end{matrix}
\end{pmatrix}$

#### Разделим вторую строчку на -3

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & 1 & 2\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
4/3a - b/3\\
c
\end{matrix}
\end{pmatrix}$

#### Вычтем из третьей строки первую, умноженную на 7

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & 1 & 2\\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
4/3a - b/3\\
c - 7a
\end{matrix}
\end{pmatrix}$

#### Сложим третью строку со второй, умноженной на 6

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
0 & 1 & 2\\ 
0 & 0 & 0
\end{matrix}\right|
\begin{matrix}
a\\ 
4/3a - b/3\\
a - 2b + c
\end{matrix}
\end{pmatrix}$

#### Для того, чтобы система была несовместной, необходимо, чтобы $a - 2b + c \ne 0$

# Системы линейных уравнений. Часть 2

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$

$\begin{pmatrix}
\left.\begin{matrix}
1 & -2 \\
3 & -4 \\ 
\end{matrix}\right|
\begin{matrix}
1\\ 
7\\
\end{matrix}
\end{pmatrix}$


$\begin{vmatrix}
1 & -2 \\
3 & -4
\end{vmatrix}=-4+6=2$

$\begin{vmatrix}
1 & -2 \\
7 & -4
\end{vmatrix}=-4+14=10$

$x_1=\frac{10}{2}=5$

$\begin{vmatrix}
1 & 1 \\
3 & 7
\end{vmatrix}=7-3=4$

$x_2=\frac{4}{2}=2$

б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

$\begin{pmatrix}
\left.\begin{matrix}
2 & -1 & 5 \\
1 & 1 & -3 \\
2 & 4 & 1 \\
\end{matrix}\right|
\begin{matrix}
10\\ 
-2\\
1\\
\end{matrix}
\end{pmatrix}$

$\Delta = \begin{vmatrix}
2 & -1 & 5 \\
1 & 1 & -3 \\
2 & 4 & 1 \\
\end{vmatrix}=43$

$\Delta_{1} = \begin{vmatrix}
10 & -1 & 5 \\
-2 & 1 & -3 \\
1 & 4 & 1 \\
\end{vmatrix}=86$

$x_1=\frac{86}{43}=2$

$\Delta_2 = \begin{vmatrix}
2 & 10 & 5 \\
1 & -2 & -3 \\
2 & 1 & 1 \\
\end{vmatrix}=-43$

$x_2=\frac{-43}{43}=-1$

$\Delta_3 = \begin{vmatrix}
2 & -1 & 10 \\
1 & 1 & -2 \\
2 & 4 & 1 \\
\end{vmatrix}=43$

$x_3=\frac{43}{43}=1$

__2*.__ Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$

$l_{21} = \frac{a_{21}}{a_{11}} = 2$<br>
$l_{31} = \frac{a_{31}}{a_{11}} = 3$

$A^{(1)} = \begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}$

$l_{32} = \frac{a^{(1)}_{32}}{a^{(1)}_{22}} = 4$

$L = \begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}$

$U = \begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$

б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$

$l_{21} = \frac{a_{21}}{a_{11}} = 2$

$l_{31} = \frac{a_{31}}{a_{11}} = 3$

$l_{41} = \frac{a_{41}}{a_{11}} = 4$

$A^{(1)} = \begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}$

$l_{32} = \frac{a^{(1)}_{32}}{a^{(1)}_{22}} = 5$

$l_{42} = \frac{a^{(1)}_{42}}{a^{(1)}_{22}} = 6$

$A^{(2)} = \begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}$

$l_{43} = \frac{a^{(2)}_{43}}{a^{(2)}_{33}} = 7$


$U = \begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$

$L = \begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

$l_{21} = \frac{a_{21}}{a_{11}} = 11/2$

$l_{31} = \frac{a_{31}}{a_{11}} = 9/2$

$A^{(1)} = \begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3/2 & -23/2 \\ 
0 & 7/2 & -19/2
\end{pmatrix}$

$l_{32} = \frac{a^{(1)}_{32}}{a^{(1)}_{22}} = 7/3$

$L = \begin{pmatrix}
1 & 0 & 0 \\ 
11/2 & 1 & 0 \\ 
9/2 & 7/3 & 1
\end{pmatrix}$

$U = \begin{pmatrix}
2 & 1 & 3 \\ 
0 & 3/2 & -23/2 \\ 
0 & 0 & 52/3
\end{pmatrix}$

$\begin{cases}
y_1 = 1 \\
11/2y_1 + y_2 = -6 \\
9/2y_1 + 7/3y_2 + y_3 = -5
\end{cases} = 
\begin{cases}
y_1 = 1 \\
y_2 = -23/2 \\
y_3 = 52/3
\end{cases}$

$\begin{cases}
2x_1 + x_2 + 3x_3 = 1 \\
3/2x_2 - 23/2x_3 = -23/2 \\
52/3x_3 = 52/3
\end{cases} = 
\begin{cases}
x_1 = -1 \\
x_2 = 0 \\
x_3 = 1
\end{cases}$

__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

$l_{11} = \sqrt{a_{11}} = 9$

$l_{21} = \frac{1}{l_{11}} \cdot a_{21} = -5$

$l_{31} = \frac{1}{l_{11}} \cdot a_{31} = 5$

$l_{22} = \sqrt{a_{22} - l^2_{21}} = 5$

$l_{32} = \frac{1}{l_{22}} \cdot (a_{32} - l_{21} \cdot l_{31}) = 2$

$l_{33} = \sqrt{a_{33} - l^2_{32} - l^2_{31}} = 3$

$L = \begin{pmatrix}
9 & 0 & 0 \\ 
-5 & 5 & 0 \\ 
5 & 2 & 3
\end{pmatrix}$

$L^T = \begin{pmatrix}
9 & -5 & 5 \\ 
0 & 5 & 2 \\ 
0 & 0 & 3
\end{pmatrix}$


$\begin{cases}
9y_1 = 531 \\
-5y_1 + 5y_2 = -460 \\
5y_1 + 2y_2 + 3y_3 = 193
\end{cases} = 
\begin{cases}
y_1 = 59 \\
y_2 = -33 \\
y_3 = -12
\end{cases}$

$\begin{cases}
9x_1 - 5x_2 + 5x_3 = 59 \\
5x_2 + 2x_3 = -33 \\
3x_3 = -12
\end{cases} = 
\begin{cases}
x_1 = 6 \\
x_2 = -5 \\
x_3 = -4
\end{cases}$

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [1]:
import numpy as np

def minor(M, c):
    B = [[1] * len(M) for i in range(len(M))]
    for l in range(len(M)):
        for k in range(len(M)):
            B[l][k] = M[l][k]
    
    B.pop(0)
    
    for i in range(len(B)):
        B[i].pop(c)
    return B


def det(M):
    X = 0
    if len(M) != len(M[0]):
        print('Matrix is not square')
    else:
        if len(M)<=2:
            return M[0][0] * M[1][1] - M[0][1] * M[1][0]
        else:
            for i in range(len(M)):
                X = X + ((-1)**i) * M[0][i] * det(minor(M, i))
        return X

    
def cramer(A,B):
    det_A = det(A)
    X = []
    if det_A == 0:
        print('The determinant of a matrix must not be zero')
        return X
    n = len(A)    
    for i in range(n):
        matrix = A.copy()
        matrix[:, i] = B
        print('\n', matrix)
        X.append(det(matrix) / det_A)
    return X

In [2]:
a = np.array([[1,-2], [3,-4]])
b = np.array([1, 7])
print(f'Матрица коэффициентов:\n{a}')
print('\n',b)
print('\nОпределитель:', det(a))
print('\nОтвет:', cramer(a, b))

Матрица коэффициентов:
[[ 1 -2]
 [ 3 -4]]

 [1 7]

Определитель: 2

 [[ 1 -2]
 [ 7 -4]]

 [[1 1]
 [3 7]]

Ответ: [5.0, 2.0]


#### Проверка

In [3]:
np.linalg.solve(a, b)

array([5., 2.])